### ISSUE TITLE
Feature: Implement variable overloading for font families

### ISSUE THREAD

**Issue by fabiosantoscode** [economist-components/component-typography#10]
If we want to use component-typography with another font (for example, a blog where the main font is comic-sans for some reason), we might want to override a font or another.

This is possible in css4 through using the second argument of `var()`, which provides a default value. Look at this for example:

https://github.com/the-economist-editorial/component-masthead/blob/master/index.css#L4

Here we see component-masthead allowing for an override, but providing its own default value, which is something we should do.

**Comment by umbobabo** [comment]
Implemented.
